import { type NextRequest, NextResponse } from "next/server";

/**
 * GET /api/captions?v={videoId}
 *
 * Fetches YouTube captions server-side to avoid CORS issues.
 * Returns available caption tracks + cues for a requested track.
 *
 * Query params:
 *   v       - YouTube video ID (required)
 *   lang    - Language code to fetch cues for (optional, returns track list if omitted)
 */

interface InnerTubeTrack {
  baseUrl?: string;
  name?: { simpleText?: string; runs?: { text: string }[] };
  languageCode?: string;
  kind?: string;
  vssId?: string;
}

interface CaptionCueRaw {
  start: number;
  duration: number;
  end: number;
  text: string;
}

/** Public Invidious instances for fallback when YouTube blocks cloud IPs */
const INVIDIOUS_INSTANCES = ["inv.nadeko.net", "yewtu.be", "invidious.nerdvpn.de"];

/** Consent cookies to bypass YouTube's GDPR consent page on EU/serverless IPs */
const YT_CONSENT_COOKIES = "CONSENT=PENDING+999; SOCS=CAESEwgDEgk2ODE3MTY1NzQaAmVuIAEaBgiA_LyuBg";

/** Fetch with AbortController timeout (safe for Vercel Hobby 10s limit) */
async function fetchWithTimeout(
  url: string,
  init: RequestInit,
  timeoutMs = 8000,
): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

function extractVideoId(input: string): string | null {
  // Already a plain ID (11 chars)
  if (/^[a-zA-Z0-9_-]{11}$/.test(input)) return input;

  try {
    const url = new URL(input);
    // youtube.com/watch?v=xxx
    if (url.searchParams.has("v")) return url.searchParams.get("v");
    // youtu.be/xxx
    if (url.hostname === "youtu.be") {
      const id = url.pathname.slice(1).split("/")[0];
      return id && /^[a-zA-Z0-9_-]{11}$/.test(id) ? id : null;
    }
    // youtube.com/embed/xxx or /shorts/xxx
    const match = url.pathname.match(/\/(embed|shorts|v)\/([a-zA-Z0-9_-]{11})/);
    if (match) return match[2];
  } catch {
    // Not a URL
  }
  return null;
}

/** Extract language code from InnerTube vssId (e.g. "a.en" → "en", ".ko" → "ko") */
function extractLangFromVssId(vssId: string | undefined): string | undefined {
  if (!vssId) return undefined;
  const match = vssId.match(/^a?\.(.+)$/);
  return match?.[1] ?? undefined;
}

/** Check if track is auto-generated based on vssId prefix ("a." = auto) */
function isAutoFromVssId(vssId: string | undefined): boolean {
  return vssId?.startsWith("a.") ?? false;
}

function extractTrackName(track: InnerTubeTrack): string {
  return (
    track.name?.simpleText ??
    track.name?.runs?.[0]?.text ??
    track.languageCode ??
    extractLangFromVssId(track.vssId) ??
    "Unknown"
  );
}

/** Map InnerTube tracks to app format, applying vssId fallbacks and filtering invalid tracks */
function mapAndFilterTracks(tracks: InnerTubeTrack[]) {
  return tracks
    .map((t) => {
      let langCode = t.languageCode;
      let isAuto = t.kind === "asr";

      if (!langCode) {
        const fromVss = extractLangFromVssId(t.vssId);
        if (fromVss) {
          console.warn(
            `[captions] languageCode missing, using vssId fallback: "${t.vssId}" → "${fromVss}"`,
          );
          langCode = fromVss;
        }
      }

      if (t.kind === undefined && t.vssId) {
        isAuto = isAutoFromVssId(t.vssId);
      }

      return {
        languageCode: langCode,
        name: extractTrackName(t),
        isAutoGenerated: isAuto,
        baseUrl: t.baseUrl,
      };
    })
    .filter(
      (t): t is typeof t & { languageCode: string; baseUrl: string } =>
        !!t.languageCode && !!t.baseUrl,
    );
}

/** Primary: extract caption data from YouTube watch page HTML */
async function fetchFromWatchPage(videoId: string) {
  const res = await fetchWithTimeout(
    `https://www.youtube.com/watch?v=${videoId}&hl=en`,
    {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9",
        Cookie: YT_CONSENT_COOKIES,
      },
    },
    8000,
  );

  if (!res.ok) {
    throw new Error(`Watch page fetch failed: ${res.status}`);
  }

  const html = await res.text();

  const marker = "var ytInitialPlayerResponse = ";
  const startIdx = html.indexOf(marker);
  if (startIdx === -1) {
    throw new Error("Could not find ytInitialPlayerResponse in watch page");
  }

  const jsonStart = startIdx + marker.length;
  let depth = 0;
  let endIdx = jsonStart;
  for (; endIdx < html.length; endIdx++) {
    if (html[endIdx] === "{") depth++;
    else if (html[endIdx] === "}") {
      depth--;
      if (depth === 0) break;
    }
  }

  const data = JSON.parse(html.substring(jsonStart, endIdx + 1));

  const videoDetails = data.videoDetails ?? {};
  const title = videoDetails.title ?? "Unknown";
  const channelName = videoDetails.author ?? "Unknown";

  const renderer = data.captions?.playerCaptionsTracklistRenderer;
  const tracks: InnerTubeTrack[] = renderer?.captionTracks ?? [];

  return {
    videoId,
    title,
    channelName,
    thumbnailUrl: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
    captionTracks: mapAndFilterTracks(tracks),
  };
}

/**
 * InnerTube client configurations for fallback chain.
 * IOS/ANDROID clients return caption track URLs without POT (exp=xpe) requirement,
 * so the timedtext cue fetching works reliably. WEB/MWEB clients and watch page
 * scraping now return URLs that require POT tokens (empty responses from timedtext API).
 * Order: IOS (most reliable for captions) → ANDROID → WEB (fallback for metadata)
 */
const INNERTUBE_CLIENTS = [
  {
    label: "IOS",
    context: {
      client: {
        clientName: "IOS",
        clientVersion: "20.03.02",
        hl: "en",
        gl: "US",
        deviceMake: "Apple",
        deviceModel: "iPhone16,2",
        osName: "iPhone",
        osVersion: "18.2.1.22C161",
      },
    },
    userAgent: "com.google.ios.youtube/20.03.02 (iPhone16,2; U; CPU iOS 18_2_1 like Mac OS X;)",
  },
  {
    label: "ANDROID",
    context: {
      client: {
        clientName: "ANDROID",
        clientVersion: "20.03.02",
        hl: "en",
        gl: "US",
        androidSdkVersion: 35,
        osName: "Android",
        osVersion: "15",
      },
    },
    userAgent: "com.google.android.youtube/20.03.02 (Linux; U; Android 15) gzip",
  },
  {
    label: "WEB",
    context: {
      client: {
        clientName: "WEB",
        clientVersion: "2.20241126.01.00",
        hl: "en",
        gl: "US",
      },
    },
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  },
] as const;

/** Try fetching caption tracks with a specific InnerTube client */
async function tryFetchWithClient(videoId: string, client: (typeof INNERTUBE_CLIENTS)[number]) {
  const res = await fetchWithTimeout(
    "https://www.youtube.com/youtubei/v1/player",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "User-Agent": client.userAgent,
        Cookie: YT_CONSENT_COOKIES,
      },
      body: JSON.stringify({
        videoId,
        context: client.context,
      }),
    },
    3000,
  );

  if (!res.ok) {
    throw new Error(`InnerTube API failed (${client.label}): ${res.status}`);
  }

  const data = await res.json();

  const videoDetails = data.videoDetails ?? {};
  const title = videoDetails.title ?? "Unknown";
  const channelName = videoDetails.author ?? "Unknown";

  const renderer = data.captions?.playerCaptionsTracklistRenderer;
  const tracks: InnerTubeTrack[] = renderer?.captionTracks ?? [];

  return {
    videoId,
    title,
    channelName,
    thumbnailUrl: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
    captionTracks: mapAndFilterTracks(tracks),
  };
}

/** Fallback: fetch title/channel from YouTube oEmbed (not affected by consent) */
async function fetchOEmbedMeta(
  videoId: string,
): Promise<{ title: string; channelName: string } | null> {
  try {
    const res = await fetchWithTimeout(
      `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`,
      {},
      3000,
    );
    if (!res.ok) return null;
    const data = await res.json();
    return {
      title: data.title ?? "Unknown",
      channelName: data.author_name ?? "Unknown",
    };
  } catch {
    return null;
  }
}

/** Parse WebVTT text into CaptionCueRaw[] */
function parseWebVTT(vtt: string): CaptionCueRaw[] {
  const cues: CaptionCueRaw[] = [];
  const lines = vtt.split(/\r?\n/);
  let i = 0;

  // Skip header (WEBVTT and any metadata lines)
  while (i < lines.length && !lines[i].includes("-->")) {
    i++;
  }

  while (i < lines.length) {
    const line = lines[i];
    const match = line.match(
      /(\d{2}):(\d{2}):(\d{2})\.(\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2})\.(\d{3})/,
    );
    if (!match) {
      // Also handle MM:SS.mmm format (no hours)
      const shortMatch = line.match(/(\d{2}):(\d{2})\.(\d{3})\s*-->\s*(\d{2}):(\d{2})\.(\d{3})/);
      if (shortMatch) {
        const start =
          Number(shortMatch[1]) * 60 + Number(shortMatch[2]) + Number(shortMatch[3]) / 1000;
        const end =
          Number(shortMatch[4]) * 60 + Number(shortMatch[5]) + Number(shortMatch[6]) / 1000;
        i++;
        const textLines: string[] = [];
        while (i < lines.length && lines[i].trim() !== "") {
          textLines.push(lines[i].trim());
          i++;
        }
        const text = textLines
          .join(" ")
          .replace(/<[^>]+>/g, "")
          .trim();
        if (text) {
          cues.push({ start, duration: end - start, end, text });
        }
      } else {
        i++;
      }
      continue;
    }

    const start =
      Number(match[1]) * 3600 + Number(match[2]) * 60 + Number(match[3]) + Number(match[4]) / 1000;
    const end =
      Number(match[5]) * 3600 + Number(match[6]) * 60 + Number(match[7]) + Number(match[8]) / 1000;
    i++;

    const textLines: string[] = [];
    while (i < lines.length && lines[i].trim() !== "") {
      textLines.push(lines[i].trim());
      i++;
    }
    const text = textLines
      .join(" ")
      .replace(/<[^>]+>/g, "")
      .trim();
    if (text) {
      cues.push({ start, duration: end - start, end, text });
    }
  }

  return cues;
}

/** Fetch caption tracks from Invidious API (bypasses YouTube cloud IP blocks) */
async function fetchTracksFromInvidious(videoId: string) {
  for (const instance of INVIDIOUS_INSTANCES) {
    try {
      const res = await fetchWithTimeout(
        `https://${instance}/api/v1/captions/${videoId}`,
        {
          headers: {
            Accept: "application/json",
          },
        },
        4000,
      );

      if (!res.ok) continue;

      const data = await res.json();
      const captions: { label: string; language_code: string; url: string }[] =
        data.captions ?? data;

      if (!Array.isArray(captions) || captions.length === 0) continue;

      // Fetch video title from Invidious video endpoint
      let title = "Unknown";
      let channelName = "Unknown";
      try {
        const videoRes = await fetchWithTimeout(
          `https://${instance}/api/v1/videos/${videoId}?fields=title,author`,
          { headers: { Accept: "application/json" } },
          3000,
        );
        if (videoRes.ok) {
          const videoData = await videoRes.json();
          title = videoData.title ?? title;
          channelName = videoData.author ?? channelName;
        }
      } catch {
        // Use defaults
      }

      console.log(
        `[captions] invidious (${instance}): found ${captions.length} track(s) for ${videoId}`,
      );

      const captionTracks = captions
        .map((c) => {
          if (!c.language_code) {
            console.warn(
              `[captions] invidious: language_code missing for "${c.label}", using label as fallback`,
            );
          }
          return {
            languageCode: c.language_code || c.label,
            name: c.label,
            isAutoGenerated: c.label.toLowerCase().includes("auto"),
            baseUrl: c.url.startsWith("http") ? c.url : `https://${instance}${c.url}`,
          };
        })
        .filter((t) => !!t.languageCode && !!t.baseUrl);

      return {
        videoId,
        title,
        channelName,
        thumbnailUrl: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
        captionTracks,
        _invidiousInstance: instance,
      };
    } catch (err) {
      console.warn(
        `[captions] invidious (${instance}) failed for ${videoId}: ${err instanceof Error ? err.message : err}`,
      );
    }
  }
  return null;
}

/** Fetch caption cues from Invidious WebVTT endpoint */
async function fetchCuesFromInvidious(
  videoId: string,
  lang: string,
): Promise<CaptionCueRaw[] | null> {
  for (const instance of INVIDIOUS_INSTANCES) {
    try {
      const res = await fetchWithTimeout(
        `https://${instance}/api/v1/captions/${videoId}?label=&lang=${lang}`,
        {},
        4000,
      );
      if (!res.ok) continue;

      const vtt = await res.text();
      if (!vtt || !vtt.includes("-->")) continue;

      const cues = parseWebVTT(vtt);
      if (cues.length > 0) {
        console.log(
          `[captions] invidious cues (${instance}): got ${cues.length} cue(s) for ${videoId}/${lang}`,
        );
        return cues;
      }
    } catch (err) {
      console.warn(
        `[captions] invidious cues (${instance}) failed: ${err instanceof Error ? err.message : err}`,
      );
    }
  }
  return null;
}

/** Fetch caption tracks: InnerTube mobile clients first (POT-free URLs), watch page fallback */
async function fetchCaptionTracks(videoId: string) {
  // Primary: InnerTube mobile clients (IOS/ANDROID return caption URLs without POT requirement)
  let lastError: Error | null = null;
  let result: {
    videoId: string;
    title: string;
    channelName: string;
    thumbnailUrl: string;
    captionTracks: {
      languageCode: string;
      name: string;
      isAutoGenerated: boolean;
      baseUrl: string;
    }[];
  } | null = null;

  for (const client of INNERTUBE_CLIENTS) {
    try {
      const r = await tryFetchWithClient(videoId, client);

      if (r.captionTracks.length === 0) {
        console.warn(
          `[captions] ${client.label}: no caption tracks returned for ${videoId}, trying next client`,
        );
        continue;
      }

      console.log(
        `[captions] ${client.label}: found ${r.captionTracks.length} caption track(s) for ${videoId}`,
      );

      result = r;
      break;
    } catch (err) {
      lastError = err instanceof Error ? err : new Error(String(err));
      console.warn(`[captions] ${client.label} failed for ${videoId}: ${lastError.message}`);
    }
  }

  // Fallback: watch page scraping (may return POT-required URLs, but still useful for metadata)
  if (!result) {
    try {
      const r = await fetchFromWatchPage(videoId);

      if (r.captionTracks.length > 0) {
        console.log(
          `[captions] watch page: found ${r.captionTracks.length} track(s) for ${videoId}`,
        );
        result = r;
      }
    } catch (err) {
      console.warn(
        `[captions] watch page failed for ${videoId}: ${err instanceof Error ? err.message : err}`,
      );
    }
  }

  // Fallback: Invidious API (works from cloud IPs where YouTube blocks InnerTube)
  if (!result) {
    try {
      const invResult = await fetchTracksFromInvidious(videoId);
      if (invResult && invResult.captionTracks.length > 0) {
        result = invResult;
      }
    } catch (err) {
      console.warn(
        `[captions] invidious failed for ${videoId}: ${err instanceof Error ? err.message : err}`,
      );
    }
  }

  // All methods failed — return empty result
  if (!result) {
    result = {
      videoId,
      title: "Unknown",
      channelName: "Unknown",
      thumbnailUrl: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
      captionTracks: [],
    };
  }

  // Supplement metadata via oEmbed if title/channelName are missing (applies to all paths)
  if (result.title === "Unknown" || result.channelName === "Unknown") {
    const oEmbed = await fetchOEmbedMeta(videoId);
    if (oEmbed) {
      if (result.title === "Unknown") result.title = oEmbed.title;
      if (result.channelName === "Unknown") result.channelName = oEmbed.channelName;
      console.log(
        `[captions] oEmbed supplement: title="${result.title}", channel="${result.channelName}"`,
      );
    }
  }

  // If we have no tracks and no useful metadata, throw the last error
  if (result.captionTracks.length === 0 && result.title === "Unknown" && lastError) {
    throw lastError;
  }

  return result;
}

/** Fetch and parse caption cues from a baseUrl, with Invidious fallback */
async function fetchCaptionCues(
  baseUrl: string,
  videoId: string,
  lang: string,
): Promise<CaptionCueRaw[]> {
  // Primary: try the timedtext baseUrl (JSON format, or WebVTT from Invidious)
  try {
    const url = new URL(baseUrl);
    url.searchParams.set("fmt", "json3");

    const res = await fetchWithTimeout(
      url.toString(),
      {
        headers: {
          "User-Agent":
            "com.google.ios.youtube/20.03.02 (iPhone16,2; U; CPU iOS 18_2_1 like Mac OS X;)",
        },
      },
      8000,
    );

    if (res.ok) {
      const text = await res.text();
      if (text) {
        // Try JSON3 (YouTube timedtext) first
        try {
          const data = JSON.parse(text);
          if (data.events) {
            const cues: CaptionCueRaw[] = [];

            for (const event of data.events) {
              if (!event.segs) continue;

              const segText = event.segs
                .map((s: { utf8?: string }) => s.utf8 ?? "")
                .join("")
                .replace(/\n/g, " ")
                .trim();

              if (!segText) continue;

              const startMs: number = event.tStartMs ?? 0;
              const durationMs: number = event.dDurationMs ?? 0;
              const start = startMs / 1000;
              const duration = durationMs / 1000;

              cues.push({
                start,
                duration,
                end: start + duration,
                text: segText,
              });
            }

            if (cues.length > 0) return cues;
          }
        } catch {
          // JSON parse failed — check if response is WebVTT (Invidious URLs return WebVTT)
          if (text.includes("-->")) {
            console.log("[captions] baseUrl returned WebVTT instead of JSON3, parsing as WebVTT");
            const cues = parseWebVTT(text);
            if (cues.length > 0) return cues;
          }
        }
      }
    }
  } catch (err) {
    console.warn(
      `[captions] timedtext fetch failed, trying invidious: ${err instanceof Error ? err.message : err}`,
    );
  }

  // Fallback: Invidious WebVTT
  const invCues = await fetchCuesFromInvidious(videoId, lang);
  if (invCues && invCues.length > 0) return invCues;

  throw new Error("Failed to fetch caption cues from both timedtext and Invidious");
}

const SENTENCE_SPLIT_RE = /(?<=[.?!。？！])\s*/;
const MERGE_MAX_DURATION = 15;
const MERGE_MAX_CHARS = 200;

/**
 * Interpolate a timestamp within a cue based on character position.
 * ASR cues have uniform speech rate assumption within each cue.
 */
function interpolateTime(cue: CaptionCueRaw, charOffset: number): number {
  if (cue.text.length === 0) return cue.start;
  const ratio = charOffset / cue.text.length;
  return cue.start + (cue.end - cue.start) * ratio;
}

/** Split each cue into sentence-level fragments, preserving timing via interpolation */
function splitCuesIntoSentences(cues: CaptionCueRaw[]): CaptionCueRaw[] {
  const fragments: CaptionCueRaw[] = [];
  for (const cue of cues) {
    const parts = cue.text.split(SENTENCE_SPLIT_RE);
    if (parts.length <= 1) {
      fragments.push(cue);
      continue;
    }
    let charPos = 0;
    for (const part of parts) {
      if (!part) continue;
      const fragStart = interpolateTime(cue, charPos);
      charPos += part.length;
      // Account for the split separator (whitespace between sentences)
      const sepMatch = cue.text.slice(charPos).match(/^\s*/);
      if (sepMatch?.[0]) charPos += sepMatch[0].length;
      const fragEnd = interpolateTime(cue, charPos);
      fragments.push({
        start: fragStart,
        end: fragEnd || cue.end,
        duration: (fragEnd || cue.end) - fragStart,
        text: part,
      });
    }
  }
  return fragments;
}

/** Merge consecutive cues at sentence boundaries for natural practice units */
function mergeCues(cues: CaptionCueRaw[]): CaptionCueRaw[] {
  if (cues.length === 0) return [];

  // First split mid-cue sentences, then merge at sentence boundaries
  const fragments = splitCuesIntoSentences(cues);

  const merged: CaptionCueRaw[] = [];
  let bufStart = 0;
  let bufEnd = 0;
  let bufTexts: string[] = [];
  let bufChars = 0;

  function flush() {
    if (bufTexts.length === 0) return;
    const text = bufTexts.join(" ");
    merged.push({
      start: bufStart,
      end: bufEnd,
      duration: bufEnd - bufStart,
      text,
    });
    bufTexts = [];
    bufChars = 0;
  }

  function startNewBuf(frag: CaptionCueRaw) {
    bufStart = frag.start;
    bufEnd = frag.end;
    bufTexts = [frag.text];
    bufChars = frag.text.length;
  }

  for (const frag of fragments) {
    // If buffer is empty, start a new one
    if (bufTexts.length === 0) {
      startNewBuf(frag);
    } else {
      const wouldDuration = frag.end - bufStart;
      const wouldChars = bufChars + 1 + frag.text.length;

      // Force flush if adding this fragment would exceed limits
      if (wouldDuration > MERGE_MAX_DURATION || wouldChars > MERGE_MAX_CHARS) {
        flush();
        startNewBuf(frag);
      } else {
        bufEnd = frag.end;
        bufTexts.push(frag.text);
        bufChars = wouldChars;
      }
    }

    // Flush at sentence boundary
    if (/[.?!。？！]$/.test(frag.text)) {
      flush();
    }
  }

  flush();

  return merged;
}

/** Debug diagnostics: test each fetch step independently */
async function runDebugDiagnostics(videoId: string) {
  const startTime = Date.now();
  // biome-ignore lint/suspicious/noExplicitAny: debug diagnostics collect heterogeneous step results
  const steps: Record<string, any> = {};

  // 1. Watch page
  try {
    const res = await fetchWithTimeout(
      `https://www.youtube.com/watch?v=${videoId}&hl=en`,
      {
        headers: {
          "User-Agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
          "Accept-Language": "en-US,en;q=0.9",
          Cookie: YT_CONSENT_COOKIES,
        },
      },
      8000,
    );
    const html = await res.text();
    const hasPlayerResponse = html.includes("var ytInitialPlayerResponse = ");
    const hasConsentForm = html.includes("consent.youtube.com") || html.includes("CONSENT");
    steps.watchPage = {
      status: res.status,
      htmlLength: html.length,
      hasPlayerResponse,
      hasConsentForm,
    };
  } catch (err) {
    steps.watchPage = {
      error: err instanceof Error ? err.message : String(err),
    };
  }

  // 2. InnerTube clients
  for (const client of INNERTUBE_CLIENTS) {
    try {
      const res = await fetchWithTimeout(
        "https://www.youtube.com/youtubei/v1/player",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "User-Agent": client.userAgent,
            Cookie: YT_CONSENT_COOKIES,
          },
          body: JSON.stringify({ videoId, context: client.context }),
        },
        3000,
      );
      const data = await res.json();
      const rawTracks: InnerTubeTrack[] =
        data.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
      steps[`innerTube_${client.label}`] = {
        status: res.status,
        hasVideoDetails: !!data.videoDetails,
        title: data.videoDetails?.title ?? null,
        hasCaptions: !!data.captions?.playerCaptionsTracklistRenderer,
        trackCount: rawTracks.length,
        rawTracks: rawTracks.map((t) => ({
          languageCode: t.languageCode ?? null,
          vssId: t.vssId ?? null,
          kind: t.kind ?? null,
          hasBaseUrl: !!t.baseUrl,
        })),
      };
    } catch (err) {
      steps[`innerTube_${client.label}`] = {
        error: err instanceof Error ? err.message : String(err),
      };
    }
  }

  // 3. Invidious instances
  for (const instance of INVIDIOUS_INSTANCES) {
    try {
      const res = await fetchWithTimeout(
        `https://${instance}/api/v1/captions/${videoId}`,
        { headers: { Accept: "application/json" } },
        4000,
      );
      if (res.ok) {
        const data = await res.json();
        const captions = data.captions ?? data;
        steps[`invidious_${instance}`] = {
          status: res.status,
          trackCount: Array.isArray(captions) ? captions.length : 0,
          tracks: Array.isArray(captions)
            ? captions.map((c: { label?: string; language_code?: string; url?: string }) => ({
                label: c.label,
                lang: c.language_code,
                hasUrl: !!c.url,
              }))
            : [],
        };
      } else {
        steps[`invidious_${instance}`] = { status: res.status, error: "Non-OK response" };
      }
    } catch (err) {
      steps[`invidious_${instance}`] = {
        error: err instanceof Error ? err.message : String(err),
      };
    }
  }

  // 4. oEmbed
  const oEmbed = await fetchOEmbedMeta(videoId);
  steps.oEmbed = oEmbed ?? { error: "Failed or returned null" };

  return {
    videoId,
    timestamp: new Date().toISOString(),
    region: process.env.VERCEL_REGION ?? "local",
    elapsedMs: Date.now() - startTime,
    steps,
  };
}

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const videoParam = searchParams.get("v");
  const lang = searchParams.get("lang");
  const kind = searchParams.get("kind");
  const merge = searchParams.get("merge");
  const debug = searchParams.get("debug");

  if (!videoParam) {
    return NextResponse.json({ error: "Missing video ID or URL (?v=...)" }, { status: 400 });
  }

  const videoId = extractVideoId(videoParam);
  if (!videoId) {
    return NextResponse.json({ error: "Invalid YouTube video ID or URL" }, { status: 400 });
  }

  // Debug mode: return diagnostics for each fetch step
  if (debug === "1") {
    const diagnostics = await runDebugDiagnostics(videoId);
    return NextResponse.json(diagnostics, {
      headers: { "Cache-Control": "no-store" },
    });
  }

  try {
    const meta = await fetchCaptionTracks(videoId);

    // Only cache responses that have caption tracks (avoid caching empty/broken results)
    const cacheHeaders =
      meta.captionTracks.length > 0
        ? { "Cache-Control": "public, max-age=3600, s-maxage=3600" }
        : { "Cache-Control": "no-store" };

    // If no lang requested, return just the track list
    if (!lang) {
      return NextResponse.json(meta, { headers: cacheHeaders });
    }

    // Find the requested track (kind=asr distinguishes auto-generated from official)
    const track = meta.captionTracks.find(
      (t) => t.languageCode === lang && (kind ? (kind === "asr") === t.isAutoGenerated : true),
    );
    if (!track) {
      return NextResponse.json(
        { error: `No caption track found for language: ${lang}` },
        { status: 404 },
      );
    }

    const rawCues = await fetchCaptionCues(track.baseUrl, videoId, lang);
    const cues = merge === "0" ? rawCues : mergeCues(rawCues);

    return NextResponse.json({ ...meta, cues }, { headers: cacheHeaders });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
