/** A single caption/subtitle cue */
export interface CaptionCue {
  /** Start time in seconds */
  start: number;
  /** Duration in seconds */
  duration: number;
  /** End time in seconds (start + duration) */
  end: number;
  /** The subtitle text */
  text: string;
}

/** Available caption track info */
export interface CaptionTrack {
  /** Language code (e.g. "en", "ko", "ja") */
  languageCode: string;
  /** Display name (e.g. "English", "Korean") */
  name: string;
  /** Whether this is auto-generated */
  isAutoGenerated: boolean;
  /** Base URL for fetching the track */
  baseUrl: string;
}

/** YouTube video metadata */
export interface VideoMeta {
  videoId: string;
  title: string;
  channelName: string;
  thumbnailUrl: string;
  captionTracks: CaptionTrack[];
}

/** Practice mode */
export type PracticeMode = "type" | "speak" | "fill";

/** Per-cue result */
export interface CueResult {
  cueIndex: number;
  /** 0-100 */
  accuracy: number;
  /** Words per minute (type mode only) */
  wpm?: number;
  /** Whether user skipped this cue */
  skipped: boolean;
}

/** Session result */
export interface SessionResult {
  videoId: string;
  videoTitle: string;
  languageCode: string;
  mode: PracticeMode;
  totalCues: number;
  completedCues: number;
  skippedCues: number;
  avgAccuracy: number;
  avgWpm?: number;
  completedAt: string;
}

/** Saved video bookmark */
export interface VideoBookmark {
  videoId: string;
  title: string;
  channelName: string;
  thumbnailUrl: string;
  lastLanguage: string;
  lastMode: PracticeMode;
  lastPlayedAt: string;
}

/** App phase */
export type Phase =
  | "url-input"
  | "loading"
  | "track-select"
  | "mode-select"
  | "practicing"
  | "session-done"
  | "error";
